name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ianwalter/pnpm:v1.4.0
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can
          # generate changelogs with the correct commits.
          fetch-depth: 0
      - name: Install
        run: pnpm i
      - name: Build
        run: pnpm run build
      - name: Changesets
        uses: changesets/action@2bb9bcbd6bf4996a55ce459a630a0aa699457f59
        with:
          publish: pnpx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
